force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client_Adress__c.field-meta.xml
<CustomField>
    <fullName>Client_Adress__c</fullName>
    <label>Client Adress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client_City__c.field-meta.xml
<CustomField>
    <fullName>Client_City__c</fullName>
    <label>Client City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client_Country__c.field-meta.xml
<CustomField>
    <fullName>Client_Country__c</fullName>
    <label>Client Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Client_ZIP__c.field-meta.xml
<CustomField>
    <fullName>Client_ZIP__c</fullName>
    <label>Client ZIP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Consignee_Adress__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Adress__c</fullName>
    <label>Consignee Adress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Consignee_City__c.field-meta.xml
<CustomField>
    <fullName>Consignee_City__c</fullName>
    <label>Consignee City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Consignee_Country__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Country__c</fullName>
    <label>Consignee Country</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Consignee_Name__c.field-meta.xml
<CustomField>
    <fullName>Consignee_Name__c</fullName>
    <label>Consignee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Consignee_ZIP__c.field-meta.xml
<CustomField>
    <fullName>Consignee_ZIP__c</fullName>
    <label>Consignee ZIP</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecordClonerTest.cls
@isTest
private class RecordClonerTest {
    @isTest
    static void testGetStringFields() {
        Invoice__c invoice = new Invoice__c(Client_Adress__c = 'Client Adress',
                                            Client_City__c = 'Client City',
                                            Client_Country__c = 'Client Country',
                                            Client_Name__c = 'Client name',
                                            Client_ZIP__c = 'Client ZIP',
                                            Consignee_Adress__c = 'Consignee Adress',
                                            Consignee_City__c = 'Consignee City',
                                            Consignee_Country__c = 'Consignee Country',
                                            Consignee_Name__c = 'Consignee Name',
                                            Consignee_ZIP__c = 'Consignee ZIP');
        insert invoice;

        String methodResult = RecordCloner.getStringFields(invoice.Id);
        String stringResult = '\'Client_Adress__c\' : \'Client Adress\' , ' +
                              '\'Client_City__c\' : \'Client City\' , ' +
                              '\'Client_Country__c\' : \'Client Country\' , ' +
                              '\'Client_Name__c\' : \'Client name\' , ' +
                              '\'Client_ZIP__c\' : \'Client ZIP\' , ' +
                              '\'Consignee_Adress__c\' : \'Consignee Adress\' , ' +
                              '\'Consignee_City__c\' : \'Consignee City\' , ' +
                              '\'Consignee_Country__c\' : \'Consignee Country\' , ' +
                              '\'Consignee_Name__c\' : \'Consignee Name\' , ' +
                              '\'Consignee_ZIP__c\' : \'Consignee ZIP\' , ' +
                              '\'External_Id__c\' : \'' + invoice.Id + '\'';

        System.assertEquals(methodResult, stringResult);
    }

    @isTest
    static void testGetInvoiceFields() {
        String lotOfFields = '';
        List<Schema.FieldSetMember> fieldsetList = RecordCloner.getInvoiceFields();
        
        System.assertEquals(fieldsetList.size(), 10);

        for(Schema.FieldSetMember field : fieldsetList) {
            lotOfFields += field.getFieldPath() + ',';
        }

        System.assertEquals(lotOfFields.contains('Client_Adress__c'), true);
        System.assertEquals(lotOfFields.contains('Client_City__c'), true);
        System.assertEquals(lotOfFields.contains('Client_Country__c'), true);
        System.assertEquals(lotOfFields.contains('Client_Name__c'), true);
        System.assertEquals(lotOfFields.contains('Client_ZIP__c'), true);
        System.assertEquals(lotOfFields.contains('Consignee_Adress__c'), true);
        System.assertEquals(lotOfFields.contains('Consignee_City__c'), true);
        System.assertEquals(lotOfFields.contains('Consignee_Country__c'), true);
        System.assertEquals(lotOfFields.contains('Consignee_Name__c'), true);
        System.assertEquals(lotOfFields.contains('Consignee_ZIP__c'), true);
    }
}