force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Client_Name__c.field-meta.xml
<CustomField>
    <fullName>Client_Name__c</fullName>
    <label>Client Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/IsDeepClone__c.field-meta.xml
<CustomField>
    <fullName>IsDeepClone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsDeepClone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/Invoice_Item__c.object-meta.xml
<CustomObject>
    <label>Invoice Item</label>
    <nameField>
        <label>Invoice Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Items</relationshipLabel>
    <relationshipName>Invoice_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Item__c/fields/Unit_cost__c.field-meta.xml
<CustomField>
    <fullName>Unit_cost__c</fullName>
    <label>Unit cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RecordCloneTriggerHandlerHelperTest.cls
@isTest
private class RecordCloneTriggerHandlerHelperTest {
    @isTest
    static void testDeepClone() {
        
        Invoice__c invoice = new Invoice__c(Client_Name__c = 'Client name 1', IsDeepClone__c = false);
        insert invoice;

        List<Invoice_Item__c> items = new List<Invoice_Item__c>();

        for(Integer i = 0; i < 3; i++) {
            Invoice_Item__c item = new Invoice_Item__c(
                Invoice__c = invoice.Id,
                Name = 'Item ' + i + ' for invoice',
                Unit_cost__c = 2.00,
                Quantity__c = 2
            );

            items.add(item);
        }
        
        insert items;

        Invoice__c copiedInvoice = new Invoice__c(Client_Name__c = 'Client name 2',
                                                  IsDeepClone__c = true,
                                                  External_Id__c = invoice.Id);

        insert copiedInvoice;

        List<Invoice_Item__c> resultItems = [SELECT Id,
                                                    Name,
                                                    Invoice__c,
                                                    Unit_cost__c,
                                                    Quantity__c
                                             FROM   Invoice_Item__c
                                             WHERE  Invoice__c =: copiedInvoice.Id];

        System.assertEquals(items.size(), resultItems.size());

        for(Invoice_Item__c resultItem : resultItems) {
            System.assertEquals(resultItem.Name.contains('for invoice'), true);
            System.assertEquals(resultItem.Unit_cost__c, 2.00);
            System.assertEquals(resultItem.Quantity__c, 2);
        }

        System.debug('Message from testDeepClone. items: ' + items);
        System.debug('Message from testDeepClone. resultItems: ' + resultItems);
        System.debug('Message from testDeepClone. items.size(): ' + items.size());
        System.debug('Message from testDeepClone. resultItems.size(): ' + resultItems.size());
    }
}